### ISSUE TITLE
mapdraw error on raspberrypi

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#120]
today, testing latest code on  raspberrypi i cannot see any maps shown.

in the console i read:
```

Traceback (most recent call last):
  File "/home/pi/drats2/D-Rats-python3_tyw/d_rats/map/mapdraw.py", line 179, in handler
    self.expose_map()
  File "/home/pi/drats2/D-Rats-python3_tyw/d_rats/map/mapdraw.py", line 393, in expose_map
    tile = center + (i - delta_w, j - delta_h)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'tuple'
```

**Comment by wb8tyw** [comment]
Can you reproduce this on demand?

What map url, center coordinates, and zoom level were in effect?

This looks like something in the map setup failed much earlier and there should have been log messages to that effect.

The default center location comes for the configuration for the user running d-rats.   I suspect that nothing is checking to see if a valid value has been entered.

**Comment by maurizioandreotti** [comment]
well, i guess it should open at my usual QTH which is always the same and
usually works fine... unlikey at the moment the map window doesn't show
anything (just the outer frame, the inside is white)

Il giorno mer 23 mar 2022 alle ore 00:09 John E. Malmberg <
***@***.***> ha scritto:
