### ISSUE TITLE
Request Mail Check crashes d-rats

### ISSUE THREAD

**Issue by wb8tyw** [wb8tyw/D-Rats#195]
In the Stations pane, right clicking on a station for a station and selecting Request Mail Check crashed D-rats.

```text
Traceback (most recent call last):

  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/main_stations.py", line 389, in _mh
    vals = prompt_for_account(self._config)

  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/main_stations.py", line 71, in prompt_for_account
    default = accounts.keys()[0]

TypeError: 'dict_keys' object is not subscriptable
```

**Comment by wb8tyw** [comment]
python3 changed dictionary handling so that the keys() method returns an iter object instead of a list.

Next problem is that while for the C implementation python3, the keys are returned in the order they were entered into the dictionary, that is not guaranteed for other implementations, and may not be guaranteed for future versions of python.

**Comment by wb8tyw** [comment]
Next odd problem, is that a widget event function that expects a box object is called with an account list object, and of course that crashes.   This could not work the python2 version.

This gets slightly farther, it gives us a list of local accounts, which you select one.
It then tries to check the e-mail on the remote system apparently using the local account, and since the remote machine had no accounts set up on it, it failed.   So now I have to ask, what is the use of this menu item?

**Comment by wb8tyw** [comment]
Even if you configure configure the account on d-rats client the system to match the remote target, it does not work because it is not configured to pass any of the access credentials to the remote target.

This menu item looks like it has not worked in a while, and it looks like making it work could be a security risk.
