### ISSUE TITLE
Config Entering latitude and longitude for home station causes exception

### ISSUE THREAD

**Issue by wb8tyw** [wb8tyw/D-Rats#222]
Entering the latitude and longitude for the home station in the config menu cases an exception.

The conversion of float is done for each keystroke, so if you totally delete the existing number, it causes an error because a blank string can not be converted to float.

**Comment by wb8tyw** [comment]
Crash:
```test
Stack (most recent call last):
  File "C:\msys64\home\malmberg\work\D-Rats\d-rats.py", line 236, in <module>
    main()
  File "C:\msys64\home\malmberg\work\D-Rats\d-rats.py", line 230, in main
    app.main()
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/mainapp.py", line 2126, in main
    self.run(None)
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/mainwindow.py", line 252, in activate_prefs
    saved = self._config.show(parent=window)
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/config.py", line 2682, in show
    result = drats_ui.run()
  File "C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 585, in run
    return Gtk.Dialog.run(self, *args, **kwargs)
  File "C:\msys64\home\malmberg\work\D-Rats\d-rats.py", line 93, in handle_exception
```
Additional info
```text
Traceback (most recent call last):
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/miscwidgets.py", line 1135, in value
    return self.parse_dd(string)
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/miscwidgets.py", line 1058, in parse_dd
    return float(string)
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/miscwidgets.py", line 1138, in value
    return self.parse_dm(string)
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/miscwidgets.py", line 1073, in parse_dm
    (_degrees, _minutes) = string.split(' ', 2)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/config.py", line 787, in changed
    conf_widget.value = "%3.6f" % entry.value()
  File "C:/msys64\home\malmberg\work\D-Rats/d_rats/miscwidgets.py", line 1141, in value
    return self.parse_dms(string)
```
