### ISSUE TITLE
event_tab crashes if changing sorting time

### ISSUE THREAD

**Issue by wb8tyw** [wb8tyw/D-Rats#233]
The Event Tab logging tab crashes if you try to change the sort order.

```text
Traceback (most recent call last):

  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/event_tab.py", line 318, in __change_sort
    self._config.set("state", "events_sort", int(srt))

  File "/usr/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)

  File "/usr/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")

TypeError: option values must be strings
```

**Comment by wb8tyw** [comment]
Fixing that issue exposes in a new issue:

```text
(d-rats.py:22213): Gtk-CRITICAL **: 09:43:48.895: gtk_tree_sortable_get_sort_column_id: assertion 'GTK_IS_TREE_SORTABLE (sortable)' failed

(d-rats.py:22213): Gtk-CRITICAL **: 09:43:48.895: gtk_tree_sortable_has_default_sort_func: assertion 'GTK_IS_TREE_SORTABLE (sortable)' failed

(d-rats.py:22213): Gtk-CRITICAL **: 09:43:48.895: gtk_tree_sortable_set_sort_column_id: assertion 'GTK_IS_TREE_SORTABLE (sortable)' failed
```
