### ISSUE TITLE
D-Rats-0.4.1_finalize - not starting on macbook

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#265]
Launching the D-Rats-0.4.1_finalize on my mac i get this error in console:

 ```
./d-rats.py                
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-0.4.1_finalize/./d-rats.py", line 37, in <module>
    from d_rats.version import __version__
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-0.4.1_finalize/d_rats/version.py", line 401, in <module>
    DRATS_VERSION_NUM = GLOBAL_VERSION.short_version
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-0.4.1_finalize/d_rats/version.py", line 111, in short_version
    self._get_short_version()
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-0.4.1_finalize/d_rats/version.py", line 101, in _get_short_version
    (cls._version['major'], cls._version['minor'],
     ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'major'
```

**Comment by maurizioandreotti** [comment]
-

**Comment by maurizioandreotti** [comment]
for any reason i didnt realize i had opened this on the former github project. i will close and reopen on the right one.
