### ISSUE TITLE
check_spelling = True

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#72]
The current setting gets to a d-rats not starting:

check_spelling = True

this is what i see in the shell window:
```
 python3 ./d-rats.py --loglevel DEBUG
02/17/2022 21:58:20:INFO:D-Rats:main: re-config option found -- Reconfigure D-rats
02/17/2022 21:58:20:INFO:Mainapp:Enabled debug log for Win32 systems
02/17/2022 21:58:20:INFO:Version:HTTP_CLIENT_HEADERS={'User-Agent': 'd-rats/0.4.00 pre-release 1'}
02/17/2022 21:58:20:INFO:QST:FeedParser not available
02/17/2022 21:58:20:INFO:DratsConfig:File C:/Users/mauri/AppData/Roaming/D-RATS-EV/d-rats.config
02/17/2022 21:58:20:INFO:MainApp:_refresh_lang: Loading locale `it'
02/17/2022 21:58:20:INFO:MainApp:_refresh_lang: Locale dir is: C:/msys64/home/mauri/d-rats-dev/D-Rats-python3_tyw/locale
02/17/2022 21:58:20:ERROR:MainApp:_refresh_lang: Messages catalog file missing  for it.  Need to use 'msgfmt tool to generate.
02/17/2022 21:58:20:INFO:MainApp:D-RATS v0.4.00 pre-release 1 starting at Thu Feb 17 21:58:20 2022 on Platform Win32Platform:
  base:       C:/Users/mauri/AppData/Roaming/D-RATS-EV
  source_dir: C:/msys64/home/mauri/d-rats-dev/D-Rats-python3_tyw
  OS version: Windows 10 (10, 0, 19041, 2, '')
02/17/2022 21:58:20:INFO:MainApp:load position from config file
02/17/2022 21:58:20:INFO:MainApp:_static_gps: Configuring the Static position: 45.800456,9.428377
02/17/2022 21:58:20:INFO:MainApp:_static_gps: Mapserver active: True ca;; IZ2LXI-X
02/17/2022 21:58:20:INFO:MainApp:preparing our gpsfix in JSON :{ "lat": "45.800456", "lng": "9.428377", "station": "IZ2LXI-X", "comments": "altitude: 0","timestamp": "2022-02-17 20:58:20"  }
02/17/2022 21:58:20:INFO:MainApp:Socket Created
02/17/2022 21:58:20:INFO:MainApp:Connecting to: localhost:9500

(d-rats.py:3488): GLib-GIO-WARNING **: 21:58:21.618: Unexpectedly, UWP app `MIGGsrl.VisualizzaFatturaElettronica_3.1.4.0_x86__aydtewdteyzge' (AUMId `MIGGsrl.VisualizzaFatturaElettronica_aydtewdteyzge!it.migg.VisFatt') supports 2 extensions but has no verbs
02/17/2022 21:58:22:INFO:MainApp:Failed to create socket.
Traceback (most recent call last):
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/mainapp.py", line 439, in callback_gps
    sock.connect((mapserver_ip, mapserver_port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
02/17/2022 21:58:22:INFO:MainApp:Socket Created
02/17/2022 21:58:22:INFO:StaticGPSSource:StaticGPSPosition: UNKNOWN reporting 45.8005,9.4284@0 ft at 21:58:22
02/17/2022 21:58:22:INFO:MainApp:load main window with self config

```

this is what i see in the log:
```
Traceback (most recent call last):
  File "C:\msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw\d-rats.py", line 257, in <module>
    main()
  File "C:\msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw\d-rats.py", line 235, in main
    app = mainapp.MainApp(safe=args.safe)
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/mainapp.py", line 385, in __init__
    self.mainwindow = mainwindow.MainWindow(self)
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/mainwindow.py", line 92, in __init__
    self.tabs["chat"] = ChatTab(wtree, config)
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/ui/main_chat.py", line 427, in __init__
    spell.prepare_TextBuffer(entry.get_buffer())
  File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/spell.py", line 229, in prepare_TextBuffer
    tag.set_property("underline", Pango.UNDERLINE_SINGLE)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Pango' object has no attribute 'UNDERLINE_SINGLE'
```

**Comment by wb8tyw** [comment]
https://github.com/wb8tyw/D-Rats/issues/66
