### ISSUE TITLE
Chat TAB - QSTs Edit

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#75]
edit button of QST does not have any effect (it should open a pop-up to edit the QST)

the console shows a line stating "Defining SQT types"

Remove and Delete buttons are working

note: in my case all buttons are shown in a correct Italian "Aggiungi", "Rimuovi" and "Modifica"

**Comment by wb8tyw** [comment]
Additional problem while attempting to reproduce:
Can not deactivate a test QST.
```text
Traceback (most recent call last):
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/main_chat.py", line 266, in _toggle_qst
    self._config.set(qst_id, "enabled", val)
  File "/usr/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

```

**Comment by wb8tyw** [comment]
Editing a QST is failing at:
```text
Traceback (most recent call last):
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/main_chat.py", line 299, in _edit_qst
    dialog = qst.QSTEditDialog(self._config, ident)
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/qst.py", line 1397, in __init__
    self._freq.child.set_text(self._config.get(self._ident, "freq"))
AttributeError: 'ComboBoxText' object has no attribute 'child'
```
This is one of the differences in the GTK-2 and GTK-3 APIs.

**Comment by wb8tyw** [comment]
Can you verify that this can be closed?

**Comment by maurizioandreotti** [comment]
solved
